# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

[package]
name = "git-cinnabar"
version = "0.6.0-a"
authors = ["Mike Hommey <mh@glandium.org>"]
edition = "2018"
license = "MPL-2.0"
repository = "https://github.com/glandium/git-cinnabar"
publish = false

[dependencies]
all_asserts = "2"
bstr = "0.2"
bzip2 = "0.4"
byteorder = "1"
crossbeam = "0.8"
cstr = "0.2"
derivative = "2"
derive_more = "0.99"
digest = "0.9"
either = "1"
getset = "0.1"
hex = "0.4"
itertools = "0.10"
libc = "0.2"
once_cell = "1"
percent-encoding = "2"
replace_with = "0.1"
sha-1 = "0.9"
structopt = "0.3"
tempfile = "3"
typenum = "1"
url = "2"
which = "4"
zstd = "0.7"

[dependencies.curl-sys]
version = "0.4"
default-features = false

[dependencies.flate2]
version = "1"
default-features = false
features = ["zlib"]

[dependencies.libz-sys]
version = "1"
features = ["static"]

[dependencies.regex]
version = "1"
default-features = false
features = ["std"]

[build-dependencies]
count-write = "0.1"
git-version = "0.3"
itertools = "0.10"
make-cmd = "0.1"
rustversion = "1.0"
tar = "0.4"
target = "1.0"
walkdir = "2"

[profile.release]
codegen-units = 1
debug = true
panic = "abort"

[profile.dev]
opt-level = 1
panic = "abort"
